# -*- coding: utf-8 -*-
"""Panaversity-Python-Class-2-Part-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HeW3LaoyPamPt8wb-kCAan5ca2vX7qqK

#**Type of num**

1. *Integer*
2.  *Float*
3. *Complex*
# AI Agent mein use:
# Jab user input aaye —
# pehle type check karo!

**How to get type of a data**
"""

# AI mein use:
# name print karny ke liye
name = "Bilal"
print(type(name))

# AI mein use:
# Age = Integer → 23
first_num = 9
print(type(first_num))

# AI mein use:
# Price = Float → 299.99
# Score = Float → 0.95
point_num = 8.0
print(type(point_num))

real_img = 4 + 3j
print(type(real_img))

"""#What is F-String

# AI Agent mein use:
# Jab user input aaye —
# pehle type check karo!
"""

name = "Asad Ali"
print(f"My name is {name}")

# F-string ka use website me user ko welcome karny ke liye kia jata ha
user_name = "Asad Ali"
print(f" Hello {user_name}! Welcome to the Website")

# other way
friend_name = "Bilal Ahmed"
print(f"My friend name is {friend_name}")

"""#*What is docstring*
1. *Use* ''' text data ''' or ''' text data '''
2. *Example*
'''
my name is asad ali
my city name is kasur
my hoby is reading good book like think and grow rich
'''
# AI mein use:
# Long prompts likhne ke liye!
# System instructions ke liye!
"""

paragraph = '''My name is Asad Ali.
I'm a student of panaversity python plyalist.
now i'm learn that how to write text data in multiple lines.'''
print(paragraph)

paragraph = """My name is Asad Ali.
I'm a student of panaversity python plyalist.
now i'm learn that how to write text data in multiple lines."""
print(paragraph)

"""#What is comment in python and how to use it and why to use it?

(i) What is a comment?
	This is # comment.

(ii) Why use it?
Code ko comment karny ke liye ya referense deny ke liye.
# Yeh comment hai — Python ignore karta hai
# Dusron ko samjhane ke liye likhte hain
# Apne future self ko bhi! 😄

(iii) How to use it?
	Use the # to comment & uncomment anything.
"""

programming_Languages = ("Python", "JavaScript")
# these lines are important for my project
print(programming_Languages[0])
print(programming_Languages[1])

"""**F-string and docsrring ka use karty howy ik message write kro**"""

user_name = ("Asad Ali", "Bilal Ahmed")
print(f"""Hello {user_name[0]},
you got a free coupon code: Happy2026

Best Regards
ChatGPT
""")

user_name = "Asad Ali"
subject = "you got a free coupon code: Happy2026"
best = "Best Regards"
name = "ChatGPT"
print(f"Hi {user_name} \n {subject} \n {best} \n {name}")

# Real AI Agent mein:

user_input = "Hello, I want to order pizza"

# Type check karo
print(type(user_input))  # str ✅

# f-string se response banao
agent_response = f"""
Dear Customer,
Your order has been received!
We will deliver soon.

Best Regards,
Pizza Bot 🍕
"""
print(agent_response)

# Docstring = System prompt likhne ka
# same concept hai!

agent_name = "Ask AsadBot"
user_name = "Bilal Ahmed"
service = "AI Automation"
message = f"""
Hello {user_name}!👋
Welcome to {agent_name}!
We Specialized in Service {service}.
How can I help you today?
Best Regards,
{agent_name}🤖"""
print(message)