# -*- coding: utf-8 -*-
"""Panaversity-Python-Class-2-Part-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13U9bVdil-6DX5BQMvdEYglBcgsR_f0cd

# ============================================
# Panaversity Python Class 2 — Part 2
# By Asad Ali — Pakistan's AI Ecosystem Creator 🇵🇰
# Date: 18 March 2026
# ============================================

# ============================================
# 1. ARITHMETIC OPERATORS
# ============================================
"""

# Addition
item1 = 90
item2 = 49
result = item1 + item2
print("Addition:", result)

# Subtraction
value1 = 89
value2 = 87
result = value1 - value2
print("Subtraction:", result)

# Multiplication
price1 = 890
price2 = 98
result = price1 * price2
print("Multiplication:", result)

# Division
item1 = 394
item2 = 390
result = item1 / item2
print("Division:", result)

# Modulus
value1 = 90
value2 = 5
result = value1 % value2
print("Modulus:", result)

# Exponentiation
item1 = 8
print("Exponentiation:", item1 ** 2)

print("=" * 35)

"""# ============================================
# 2. GOLDEN RULE — EVEN / ODD
# num % 2 == 0 → Even ✅
# num % 2 == 1 → Odd  ✅
# ============================================
"""

# Single number check — Even
num = 15
if num % 2 == 0:
    print(f"{num}: Is Even ✅")
else:
    print(f"{num}: Is Odd ❌")

# Single number check — Odd
num = 10
if num % 2 == 0:
    print(f"{num}: Is Even ✅")
else:
    print(f"{num}: Is Odd ❌")

print("=" * 35)

"""# ============================================
# 3. EVEN NUMBERS — 1 to 22
# ============================================
"""

even_count = 0
for num in range(1, 23):
    if num % 2 == 0:
        print(f"{num}: Is Even ✅")
        even_count = even_count + 1

print(f"Total Even Numbers: {even_count}")

print("=" * 35)

"""# ============================================
# 4. ODD NUMBERS — 1 to 22
# ============================================
"""

odd_count = 0
for num in range(1, 23):
    if num % 2 != 0:
        print(f"{num}: Is Odd ❌")
        odd_count = odd_count + 1

print(f"Total Odd Numbers: {odd_count}")

print("=" * 35)

"""# ============================================
# 5. ASSIGNMENT — CHAAND TAARA KHAN
#    🍮 Rabri Party Calculator
#**Problem:**
Chaand Taara Khan apne institute mein Rabri party de raha hai.


Tumhe calculate karna hai:

Total log kitne aayenge?
Kitni Rabri chahiye — grams aur kg mein?

#Given Data:

Faculty members: 12

Administrative staff: 4

Students: 100

Absent: 15

Rabri per person: 250g
# ============================================
"""

# Given data
faculty_members = 12
administrative_staff = 4
institute_students = 100
absent = 15
rabri_per_person = 250  # grams

# Step 1: Total attending members
total_members = (faculty_members +
                 administrative_staff +
                 institute_students - absent)

# Step 2: Total rabri in grams
total_rabri_gram = total_members * rabri_per_person

# Step 3: Convert grams to KG
total_rabri_kg = total_rabri_gram / 1000

# Step 4: Print results
print("=" * 35)
print("   RABRI PARTY CALCULATOR 🍮")
print("=" * 35)
print(f"Total Members Attending : {total_members}")
print(f"Rabri Per Person        : {rabri_per_person}g")
print(f"Total Rabri Needed      : {total_rabri_gram}g")
print(f"Total Rabri Needed      : {total_rabri_kg}kg")
print("=" * 35)
print("Party ready hai! Bismillah! 🎉")