# -*- coding: utf-8 -*-
"""Panaversity_Python_Class-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HaDgqni3n9Wggzp3LKMzu5jwAxDV9-3E

**Variable (Data ka name)**
"""

name = "Asad Ali"
age = 23
city = "Kasur"
favorite_Heros= "Mehmed Fatih", "Sultan Abdulhamid", "Sultan Sulman Qanoni"
favorite_Food = "Aplle", "Mango"
print(name,age,favorite_Heros,favorite_Food,)

"""**String (Text data)**"""

name = "Asad Ali"
print(name)

"""**Number (Numeric data )**"""

age = 24
print(age)

"""**concatenation (Strings jodna)**"""

first_name = "Aasd"
last_name = "Ali"
print(first_name + " " + last_name)

"""**Print (Screen pe Dekhana)**
**Print()**
"""

print()

"""**🔥 AI Agent Connection — Yeh Kyun Important Hai** — **Tumne aaj yahi seekha**
— **#bas AI context mein!**
"""

# Real AI Agent mein yeh hota hai:

user_name = "Asad"                                   #Variable
user_message = "Hello can you help me"               #String
user_Age = 24                                        #Number
# Agent Respone
Respose = "Hello " + user_name + " How can i help you"
print(Respose)
# Output: Hello Asad! How can I help?
# Humne aaj yahi seekha —
# bas AI context mein! 🤖

"""**Apny 3 Pakistani Heroes ka Name ka Ik Program Bano and F-string ka use kro**"""

hero1 = "Allama Muhammad Iqbal"
hero2 = "Quaid e Azam Muhammad Ali Jinnah"
hero3 = "Sir Zia Khan"
hero4 = "Sir Faizan Nawaz"
print("My Favorites Heroes")
print(f"1. {hero1}")
print(f"2. {hero2}")
print(f"3. {hero3}")
print(f"4. {hero4}")

"""## 📊 Hamari Overall Progress:
```
Day 1 — Aaj:
├── ✅ Variables
├── ✅ Strings  
├── ✅ Numbers
├── ✅ Concatenation
├── ✅ Print function
└── ✅ Panaversity Class 1 Complete!
"""
