# -*- coding: utf-8 -*-
"""Panaversity-Python-Class-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goXTf1SlAbo6ZqwmF4u0k3KB86aAU_HN
"""

# ============================================
# Panaversity Python Class 3
# By Asad Ali — Pakistan's AI Ecosystem Creator
# Date: 23 March 2026
# ============================================

# ============================================
# 1. BOOLEAN DATA TYPE
# ============================================
python_class_complete = True
python_class_pending = False
print(f"Welcome to Next Class: {python_class_complete}")
print(f"Complete Before Moving: {python_class_pending}")

print("=" * 40)

# ============================================
# 2. COMPARISON OPERATORS
# ============================================

a = 20
b = 90
print(f"a == b : {a == b}")   # False
print(f"a != b : {a != b}")   # True
print(f"a >= b : {a >= b}")   # False
print(f"a <= b : {a <= b}")   # True
print(f"a <= 90: {a <= 90}")  # True
print(f"a < b  : {a < b}")    # True

print("=" * 40)

# ============================================
# 3. IF / ELSE
# ============================================

# Park entry
age_limitations = 18
my_age = 17
if my_age >= age_limitations:
    print("You're Allowed For Entry ✅")
else:
    print("You're Not Allowed For Entry ❌")
# Marriage hall
my_age = 19
if my_age >= age_limitations:
    print("You're Allowed For Entry ✅")
else:
    print("You're Not Allowed For Entry ❌")

print("=" * 40)

# ============================================
# 4. ELIF — Extra Bonus
# ============================================

extra_bonus = 30
person1 = 29
person2 = 30

# person1 — not eligible
if person1 >= extra_bonus:
    print("Person1: Eligible for bonus ✅")
else:
    print("Person1: Not eligible ❌")

# person2 — eligible
if person2 >= extra_bonus:
    print("Person2: Eligible for bonus ✅")
else:
    print("Person2: Not eligible ❌")

print("=" * 40)

# ============================================
# 5. AGE CLASSIFIER
# ============================================

age = int(input("Enter Your Age: "))
if age < 18:
    print("You're a minor person")
elif age <= 35:
    print("You're a young person")
elif age <= 60:
    print("You're a middle aged person")
else:
    print("You're a senior citizen")

print("=" * 40)

"""# ============================================
# 6. LOGICAL OPERATORS — and, or, not
# ============================================

# AND — dono True hone chahiye
# OR  — ek bhi True ho
# NOT — ulta kar deta hai

"""

# ============================================
# 7. INPUT FUNCTION
# ============================================

name = input("What is Your Name? ")
print(f"Welcome: {name}")

age = input("What is Your Age? ")
print(f"Your age is: {age}")

print("=" * 40)

# ============================================
# 8. ASSIGNMENT — Food Decision
# ============================================

is_Hungary = True
burger_lover = True
pizza_lover = False

if is_Hungary and (burger_lover or pizza_lover):
    print("Let's order the fast-food! 🍔")
elif is_Hungary:
    print("Let's go to sleep without eating 😴")
else:
    print("Not hungry at all! 😊")

# Real AI Agent mein yahi hota hai!

user_verified = True
subscription_active = True
is_premium = False

if user_verified and subscription_active:
    if is_premium:
        print("Premium features unlock! 💎")
    else:
        print("Basic features available ✅")
else:
    print("Please login first! ❌")

# Yeh exactly wahi logic hai jo
# ChatGPT, Claude jaise AI
# systems use karte hain! 🔥