# -*- coding: utf-8 -*-
"""Class 4 - Lists & List Methods in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tkHNS3PpelRKqZjBARH_pa87m-A3KofL

# ============================================
# Panaversity Python Class 4 — Lists
# By Asad Ali — Pakistan's AI Ecosystem Creator
# Date: 24 March 2026
# =======================================

## **Lists in Python**

# A **list** is a built-in data type in Python that represents an ordered collection of items. Lists are:


# *   **Ordered**: The items have a defined order, and that order will not change. You can access items by their index.


# *   **Changeable (Mutable)**: You can change, add, and remove items after the list has been created.


# *   **Allow Duplicates**: Lists can have items with the same value.


# *   **Heterogeneous**: A single list can contain items of different data types (e.g., integers, strings, objects).

# Lists are created using square brackets []
"""

# ============================================
# 1. LIST CREATION
# ============================================
my_list = [1, "hello", 3.14, True]
print(my_list)

print("=" * 40)

"""# Common List Methods in Python

# Python lists come with several built-in methods that allow you to manipulate them.


# Here are some of the most commonly used ones:

# List Index
1. List Index 0 se start hota hai
"""

# ============================================
# 2. LIST INDEX — 0 se start hota hai
# ============================================
my_list: list[str] = ["apple", "banana",
                       "cherry", "mango",
                       "elderberry"]
print(f"Index 0: {my_list[0]}")   # apple
print(f"Index 1: {my_list[1]}")   # banana
print(f"Index -1: {my_list[-1]}") # elderberry

print("=" * 40)

"""# Leanth
LENGTH — 1 se count hota hai
"""

# ============================================
# 3. LENGTH — 1 se count hota hai
# ============================================
my_list: list[str] = ["apple", "banana",
                       "cherry", "mango",
                       "elderberry"]
print(f"Length: {len(my_list)}")  # 5

print("=" * 40)

"""# List Slicing
Slice index se work karta ha mean ke 0 se start ho gi value is me
"""

# ============================================
# 4. LIST SLICING
# ============================================
my_list: list[str] = ["apple", "banana",
                       "cherry", "mango",
                       "elderberry"]
print(f"Slicing [0:3]: {my_list[0:3]}")  # first 3
print(f"Slicing [0:5]: {my_list[0:5]}")  # all 5

print("=" * 40)

"""># Membership Check


"""

# ============================================
# 5. MEMBERSHIP CHECK
# ============================================
my_list: list[str] = ["apple", "banana",
                       "cherry", "mango",
                       "elderberry"]
print(f"'date' in list: {'date' in my_list}")        # False
print(f"'apple' in list: {'apple' in my_list}")      # True
print(f"'apple' not in list: {'apple' not in my_list}") # False

print("=" * 40)

"""# Adding Item in list"""

# ============================================
# 6. ADD ITEMS
# ============================================
my_list: list[str] = ["apple", "banana",
                       "cherry", "mango",
                       "elderberry"]
# append — end mein add
my_list.append("flour")
print(f"After append: {my_list}")

# insert — specific jagah add
my_list.insert(0, "Oil")
print(f"After insert: {my_list}")

print("=" * 40)

"""# Remove Item from the list"""

# ============================================
# 7. REMOVE ITEMS
# ============================================
my_list: list[str] = ["apple", "banana",
                       "cherry", "mango",
                       "elderberry", "flour"]
# remove — naam se hatao
my_list.remove("flour")
print(f"After remove: {my_list}")

# pop — index se hatao
my_list.pop(0)
print(f"After pop(0): {my_list}")

print("=" * 40)

"""# Clear All List"""

# ============================================
# 8. CLEAR — sab kuch hatao
# ============================================
my_list: list[str] = ["apple", "banana",
                       "cherry", "mango",
                       "elderberry"]
my_list.clear()
print(f"After clear: {my_list}")  # []

print("=" * 40)

"""# Sort alphabetical order"""

# ============================================
# 9. SORT — alphabetical order
# ============================================
my_list: list[str] = ["apple", "banana",
                       "cherry", "mango",
                       "elderberry"]
my_list.sort()
print(f"After sort: {my_list}")

"""# 🤖 AI Agent Connection:

# Real AI Agent mein Lists use:

# Chat history store karna
chat_history = []
chat_history.append("User: Hello!")
chat_history.append("Agent: Hi! How can I help?")
chat_history.append("User: What is Python?")

print(f"Total messages: {len(chat_history)}")
print(f"Last message: {chat_history[-1]}")

# Yeh exactly wahi hai jo
# ChatGPT conversation
# store karta hai! 🔥
```


# 📊 List Methods — Quick Reference:
```
METHOD          KYA KARTA HAI
───────────────────────────

append(item)  → end mein add

insert(i,item)→ specific jagah

remove(item)  → naam se hatao

pop(index)    → index se hatao

clear()       → sab hatao

sort()        → alphabetical

len(list)     → total count

list[0]       → index se access

list[0:3]     → slicing

"x" in list   → check karo
"""

# Chat history store karna
chat_history = []
chat_history.append("User: Hello!")
chat_history.append("Agent: Hi! How can I help?")
chat_history.append("User: What is Python?")

print(f"Total messages: {len(chat_history)}")
print(f"Last message: {chat_history[-1]}")